name: kagga
description: "Access all Mankutimmana kagga in a simple app"
publish_to: 'none'
version: 2.1.1+26

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.1
  path: ^1.9.0
  flutter_platform_widgets: ^7.0.1
  flutter_localizations:
    sdk: flutter
  package_info_plus: ^8.1.2
  webview_flutter: ^4.7.0
  url_launcher: ^6.1.14
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2

flutter_icons: 
  android: true
  ios: true
  image_path: "assets/kagga_icon.png"
  min_sdk_android: 21
  prefix: ""

flutter:
  uses-material-design: true
  assets:
    - assets/kagga_v5.sqlite
    - assets/images/
    - assets/images/favorite_thumb.png
  generate: true

l10n:
  arb-dir: "lib/l10n"
  template-arb-file: "app_en.arb"
  output-localization-file: "app_localizations.dart"