name: kagga
description: "Access all Mankutimmana kagga in a simple app"
publish_to: 'none'
version: 2.0.1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.1
  path: ^1.9.0
  flutter_platform_widgets: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/kagga_icon.png"
  min_sdk_android: 21
  prefix: ""

flutter:
  uses-material-design: true
  assets:
    - assets/kagga_v5.sqlite